### ISSUE TITLE
Miraclebox Twin+ RCU Picture in Wizard

### ISSUE THREAD

**Issue by miraclebox-git** [OpenPLi/enigma2#1034]
Hello,

Little cosmetic change as requested by OpenPli to make boxtype as own:

https://github.com/miraclebox-git/enigma2/commit/5ef9c8f8b0deb50093643329f1bbe06073fdea63

Thanks !

**Comment by WanWizard** [comment]
https://github.com/OpenPLi/enigma2/commit/b3cce9bd4109839c760f01c4bd4a5aaf7b0cbb2d
