### ISSUE TITLE
No radio background for Radio stream

### ISSUE THREAD

**Issue by robertczw** [OpenPLi/enigma2#1218]
In normal Radio channel this parameter mean Radio channel:
#SERVICE 1:0:**2**:1CA0:1CE8:71:820000:0:0:0:
for this type of services radio background is working correctly.
For the Radio Internet stream:
#SERVICE 4097:0:**2**:0:0:0:0:0:0:0:http%3a//s1.slotex.pl%3a7446/:Radio Września
they are no Radio background.

It is normal, or it is an error?

**Comment by athoik** [comment]
Closed via https://github.com/OpenPLi/enigma2/commit/f36a92773feddc9cdbf48889a73cc6b9ab16a362
