### ISSUE TITLE
Duplicate and wrong text on "HarddiskSetup" screen

### ISSUE THREAD

**Issue by nautilus7** [OpenPLi/enigma2#1241]
Commit https://github.com/OpenPLi/enigma2/commit/f440a6367140257895f20eb0c2c4f482d2af82e9 is totally wrong!!!

Red button takes its label from `self["initializetext"] = Label(text)` and can be either "Initialize" or "Check". It is associated with the "hddQuestion" funtion. 

With this commit, there is also a "Cancel" text that displays on top of these labels, because you added the "key_red button.  The red button does not cancel anything, though. Just look into the code. Red button proceeds with the action. 

Also, you added the "key_green" button, but there is no action associated with this. Also there is nothing to "save". It doesn't make sense.

So, either revert this commit, or move the "hddQuestion" to the green button, and rename "initializetext" (red button) to "key_red".

**Comment by RobvanderDoes** [comment]
Green button can be added as "execute", see https://github.com/OpenViX/enigma2/commit/623fa1db97ad4a96413dd53a1191d97c1b9ce55e  as exemple.

**Comment by nautilus7** [comment]
But there is no function associated to the green button. The green button doesn't do anything. The actual function is done with the red button and is named either "Initialize" or "Check". 

Now there is a wrong "Cancel" label on top of these, and a "Save" label in the green button, which doesn't do anything.

Please read the code.

**Comment by RobvanderDoes** [comment]
Yes, you're right.

**Comment by nautilus7** [comment]
I made a fix with moving the action to the green button and making the red button to cancel. I also added a title for each screen (there wasn't any), and adjusted the default skin.

**Comment by RobvanderDoes** [comment]
Thanks, I cherry-picked your fix as well.
