### ISSUE TITLE
Search on tittle and EPG of recorded movies

### ISSUE THREAD

**Issue by joniale** [OpenPLi/enigma2#1243]
Dear Developers,
Sometimes an autotimer records the same chapter many times under the same name o very similar names. It would be good to have the option to search and filter the matches in tittle or EPG information for the recorded movies. In that way, we can easily see/check the **recorded chapters that are duplicated**. Besides, it makes easy to find specific chapters. 
The search should have the option to include subfolders.
Besides, it would be good to have the option to s**elect multiple movie files to be deleted/copied/moved** from the Openwebif interface.
Best regards,
Joniale

**Comment by WanWizard** [comment]
We don't maintain OpenWebIf, please add any feature requests for that to https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues

**Comment by joniale** [comment]
I have already included this request under the openwebif thread.
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/758
Thanks

Anyway this ticket also applies to be able to search only on the EPG of the movie file sections directly on the enigma box. I think this is not currently possible.
