### ISSUE TITLE
A Powertimer shuts down the box during streaming from openwebif

### ISSUE THREAD

**Issue by joniale** [OpenPLi/enigma2#1246]
Dear Developers,

It would be good if you could configure your power timer (hibernate) to avoid its execution in case the box is being streamed from any place, e.g. openwebif or other box. This should be easy to detect. Another option would be to create a pop up window in the openwebif interface so that the user is requested to confirm the power timer.  This is in the same way it is currently done in the enigma box.

Lastly, it would be good to have a wakeonlan feature in the enigmabox so that we are able to wake the box from hibernate mode sending a LAN command.  Currently, this only work for standby mode.

Best regards,
joniale

**Comment by WanWizard** [comment]
WoL needs hardware support, so either the box does it (and it already works), or it will never happen.

**Comment by joniale** [comment]
I have included this request at least what is related to Openwebif in the Openwebif thread
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/760

Regarding WoL there are already some boxes with that hardware functionality.
Below, a link how this WoL feature is already used for Vu plus boxes
https://www.vuplus-support.org/wbb4/index.php?thread/50733-wake-on-lan-anleitung/
They do this by using the fritzbox router as a proxy for sending the WoL command.
Maybe, it would be possible that the enigmabox could detect directly an incoming URL request from a local webbrowser. It could be possible to store that URL script request in favorites and use it to wake the box.
Thanks anyway!

**Comment by WanWizard** [comment]
WoL is a local segment ethernet packet. It requires a physical connection between the ethernet PHY and the front processor, which is responsible for waking up the box. If this connection is not there, it will never work, as the box is switched off.

**Comment by joniale** [comment]
Yes i understand. There are some boxes that supports WoL as i commented  in my previous email.  That means, there are enigma2 compatible boxes that have that hardware. 
 I guess a PC connected to the box by LAN could generate that package. The question is if it would be easy to generate that package and if that could be just a composed URL that can be saved in favorites or it needs to be something more complex and a external program needs to be created. That script could be provided automatically by the openwebif and can be stored in the PC for future usage.
If you say that there are no many boxes that supports that and it is not worth to develop that feature then i understand. However, **the WoL is only a part of this ticket.** This ticket is really about poping a message on the openwebif interface so that users can cancel the powertimer. 

Most of the streaming software only buffer miliseconds of the source file. It is not downloading the whole file and then playing it. Therefore, it should be possible to detect if there is a streaming ongoing by spying the outgoing ethernet interface. If something is outgoing to any other IP then is is being used.

**Comment by WanWizard** [comment]
What exactly do you want to do with this URL? That is the part I don't get. The box is off, nothing on the box is available to respond to any ethernet packet, no matter what OSI layer the packet is using and what protocol is inside it.

**Comment by joniale** [comment]
As they describe in this link https://www.vuplus-support.org/wbb4/index.php?thread/50733-wake-on-lan-anleitung/ (german), they can do WoL from deep standby. 
I see it would be difficult to code directly in enigma2. However, they already did. They modified the enigma2 image to include WoL on ViT, maybe the code can be reused.
I **guess** that the modification means keeping a small process looking for the WoL ethernet in deep standby. Therefore, not everything is off. The limitation for WoL comes from the enigma2 image not from the hardware. To generate the WoL packet they use **applications** e.g.SleepOver, it seems that a simple URL will not do that and WoL requires some more complex protocol.

**Comment by WanWizard** [comment]
VTI violates the GPL license, and doesn't publish its code.

As said, WoL is a hardware implementation, not a software implementation. When WoL is enabled, the ethernet interface stays powered on, and when it sees the specially formed WoL packet arrive for it's MAC address, is sends a signal to the front processor to simulate a power on keypress. This signal goes via a wire between the interface and the front processor.

WoL support is implemented in OpenPLi since sometime 2014.
