### ISSUE TITLE
Can't build with SDL, consider SDL2?

### ISSUE THREAD

**Issue by technic** [OpenPLi/enigma2#1359]
Hi,
Was trying to build enigma2 --with-libsdl, but it doesn't compile (develop branch). I have a fork which has SDL2 support and it also can output gstreamer video to via SDL2 surfaces.
It is now based on old release-4 branch and the code needs some polishing. Let me know if you are interested, shall I try to propose the PR?

**Comment by athoik** [comment]
Sounds interesting!

Recently I compiled enigma2 under ubuntu-trusty (since travis-ci uses it), but using vga framebuffer isn't great.

So SDL2 should be much better.

**Comment by technic** [comment]
You can see my approach here https://github.com/technic/e2testBox - these are scripts for virtualbox.

**Comment by technic** [comment]
now sdl1 can be compiled https://github.com/OpenPLi/enigma2/pull/1581
