### ISSUE TITLE
Authentication for streaming asks for login credentials despite it is disabled

### ISSUE THREAD

**Issue by Pr0metheus2** [OpenPLi/enigma2#1360]
Hi,
in OpenWebIf, I have enabled HTTP Authentication and Streaming authentication is Off. 

When I run streaming, I have to always fill in credentials (name and password) - they are required despite "Enable authentication for streaming" is Off. Is this some kind of bug?

Regards

**Comment by littlesat** [comment]
I think you should consider using VPN... having a password on owif is not really recommended

**Comment by WanWizard** [comment]
@littlesat, I can't agree with that. There are plenty of reasons to have a password on OWIF. You probably mean either use a password on streaming or use a VPN, but that is only in case @Pr0metheus2 wants to stream over the internet. On the local LAN, that is not needed.

@Pr0metheus2, I can't replicate this, on my box it works as designed. I am prompted for a password when I open the webif, and when I click on the streaming icon in front of a channel, VLC opens and the stream starts. Even with authentication that should work, as OWIF has implemented a secure session key for this, so a username/password is only needed when you stream without using OWIF.

**Comment by Pr0metheus2** [comment]
Try to replicate according to my settings, please. Authentication for streaming is off, therefore username and password sholdn't be required.

OpenWebIf Setting (Restart Enigma after OWIF setting change):
![owif setting](https://user-images.githubusercontent.com/9161285/38126126-c7bdb2e8-33ee-11e8-8f6b-80cda4e8422d.jpg)

Streaming icon:
![streaming1](https://user-images.githubusercontent.com/9161285/38126130-cb41265c-33ee-11e8-8ea8-b2603abc6b1b.PNG)

Request for credentials:
![streaming2](https://user-images.githubusercontent.com/9161285/38126131-cda518c2-33ee-11e8-8ad9-310ae5e31f7b.PNG)

Content of the streaming file:
![streaming_file](https://user-images.githubusercontent.com/9161285/38126260-b21a3aa0-33ef-11e8-8206-231ce5c8a0bd.PNG)

**Comment by WanWizard** [comment]
Ah, you're not streaming, your transcoding. Transcoding is done via the streamproxy, which is a process external to OWIF, it has no clue what the settings there are.

@eriksl, this is correct?

Having said that, I've done what you asked, but I don't get a password prompt, not on streaming and not on transcoding (HD2400, 6.1-release).

**Comment by Pr0metheus2** [comment]
@WanWizard Do you have the "Enable HTTP Authentication" option set to Yes? If No, login is not required for streaming.
(VU+ Solo2, 6.1 rel.)

**Comment by WanWizard** [comment]
Yes, identical to your screenshot, and tested after an Enigma restart, like you requested.

**Comment by Pr0metheus2** [comment]
Then it looks like this is specific bug for VU+ receivers.

**Comment by WanWizard** [comment]
Possible, they have a different streamproxy setup afaik, perhaps @eriksl can comment.
