### ISSUE TITLE
GraphMultiEPG Inconsistent with imdb or tmbd

### ISSUE THREAD

**Issue by fairbird** [OpenPLi/enigma2#1411]
If I have install imdb or tmbd plugin then I got crash if I open GraphMultiEPG and exit ..

>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/GraphMultiEPG/GraphMultiEpg.py", line 1109, in closeScreen
    self.zapFunc(None, zapback = True)
  File "/usr/lib/enigma2/python/Plugins/Extensions/GraphMultiEPG/plugin.py", line 18, in zapToService
    if Servicelist.startServiceRef is None:
AttributeError: 'NoneType' object has no attribute 'startServiceRef'

**Comment by WanWizard** [comment]
I can't reproduce that, with IMDB installed. What is your exact setup?

**Comment by fairbird** [comment]
I have never setup any plugin..
Just download it and I did not open it yet (Just for try)
Directly after restart enigma2 I have opened GraphMultiEPG and close it then I got crash ..

With old version of GraphMultiEPG plugin (No crash)

> def zapToService(service):
	if not service is None:
		if Servicelist.getRoot() != epg_bouquet: #already in correct bouquet?
			Servicelist.clearPath()
			if Servicelist.bouquet_root != epg_bouquet:
				Servicelist.enterPath(Servicelist.bouquet_root)
			Servicelist.enterPath(epg_bouquet)
		Servicelist.setCurrentSelection(service) #select the service in Servicelist
		Servicelist.zap()

**Comment by WanWizard** [comment]
With "setup" I mean which box, which OpenPLi version, plugin from the feed of installed from elsewhere, etc.

**Comment by fairbird** [comment]
With DM800, DM800se my build images
and Solo 4K from pli team download
openpli-6.1-release
Yes of course plugin from feed

**Comment by WanWizard** [comment]
Sorry, I can't reproduce it. Works fine here. It looks like zapService() is called without a service, but why would that method be called if you just press Exit? It doesn't need to zap?

**Comment by fairbird** [comment]
maybe because I have add BlackHole feature in channelselection if I open GraphMultiEPG from channels list selection?!

> def keyNumberGlobal(self, number):
        unichar = self.numericalTextInput.getKey(number)
        charstr = unichar.encode('utf-8')
        if config.misc.deliteepgbuttons.value:
            if unichar == '1':
                self.session.openWithCallback(self.ShowsearchNab, VirtualKeyBoard, title='Enter event to search', text='')
            elif unichar == '2':
                self.Show2Nab()
            elif unichar == '3':
                self.Show3Nab()
            elif unichar == '4':
                self.session.open(Nab_EpgSearchLast)
        elif len(charstr) == 1:
            self.servicelist.moveToChar(charstr[0])

> def Show3Nab(self):
        myplugin = ''
        for p in plugins.getPlugins(where=PluginDescriptor.WHERE_EVENTINFO):
            nam = p.name
            pos = nam.find('EPG')
            if pos != -1:
                myplugin = p

        if myplugin:
            myplugin(session=self.session, servicelist=self)

But the feature works just fine (Only If I install imdb or tmbd plugin) I have that issue...
Thank you

**Comment by fairbird** [comment]
I have fix it by  add try: and except:

> def zapToService(service, preview = False, zapback = False):
     try:
	if Servicelist.startServiceRef is None:
		Servicelist.startServiceRef = Session.nav.getCurrentlyPlayingServiceOrGroup()
	if not service is None:
		if not preview and not zapback:
			if Servicelist.getRoot() != epg_bouquet:
				Servicelist.clearPath()
				if Servicelist.bouquet_root != epg_bouquet:
					Servicelist.enterPath(Servicelist.bouquet_root)
				Servicelist.enterPath(epg_bouquet)
			Servicelist.setCurrentSelection(service)
		if not zapback or preview:
			Servicelist.zap(not preview, preview, ref=preview and service or None)
	if (Servicelist.dopipzap or zapback) and not preview:
		Servicelist.zapBack()
	if not preview:
		Servicelist.revertMode = None
		Servicelist.startServiceRef = None
		Servicelist.startRoot = None
     except:
             pass

> def reopen(answer):
     try:
	if answer is None:
		runGraphMultiEpg()
	else:
		global ref
		if ref:
			global Servicelist
			Servicelist.setCurrentSelection(ref)
		closed(answer)
     except:
             pass

You can close it now .. Thank you
