### ISSUE TITLE
Disable Zgemma H7 illuminated logo

### ISSUE THREAD

**Issue by mcfly822** [OpenPLi/enigma2#1462]
Is there any opportunity to make an option to disable the illuminated AirDigital logo on Zgemma H7 (H7S and H7C) boxes?
It is now off only when the box is in deep sleep. In standby, it is always on.

**Comment by ims21** [comment]
you must write to Zgemma, if it will be added into drivers or if it is possible... may be, that this annoying logo is permanently powered ...

**Comment by mcfly822** [comment]
Ok, thank you!
@zgemma-star , can you please give some information about this?
