### ISSUE TITLE
WHERE_MAINMENU is not implemented

### ISSUE THREAD

**Issue by technic** [OpenPLi/enigma2#1586]
Hi,
Shall we implement support for WHERE_MAINMENU option for PluginDescriptor?
Currently it does nothing.

**Comment by littlesat** [comment]
It is possible that plug-ins dump their entry point in the main menu... so why is this needed?

**Comment by technic** [comment]
I don't know the history of PluginDescriptor, but somebody created WHERE_MAINMENU flag, wich is never used. It is confusing. 
And using WHERE_MENU has a bit complicated syntax.

**Comment by littlesat** [comment]
Can be removed this definition as there is another way to show plug-ins in the mainmenu

**Comment by littlesat** [comment]
When you want to have quick access to a plugin use extensions menu instead and don’t ‘destroy’ the (main) menu (structure)
