### ISSUE TITLE
VirtualKeyboard crash press key TEXT

### ISSUE THREAD

**Issue by norhap** [OpenPLi/enigma2#1679]
latests commits virutalkeyboard we have a crash when we press key **text**.

log crash:
line 616 markSelectedKey:
`self.list[self.selectedKey / self.keyboardWidth].append(MultiContentEntryPixmapAlphaBlend(pos=(x, 0), size=(self.key_sel.size().width(), self.height), png=self.key_sel))`

AttributeError: 'NoneType' object has no attribute '**size**'

**Comment by IanSav** [comment]
This crash is usually caused by the vkey_* files not being in the specified location.  Please check the documentation /doc/VIRTUALKEYBOARD and ensure that all the images are available.

**Comment by norhap** [comment]
yes lanSav, you can close the ticket, my skin ( adapt screen and add png) was not adapted for the new VK changes.

**Comment by IanSav** [comment]
Thank you for the confirmation of trigger for the crash.

Please keep an eye on this forum thread to follow the changes for VirtualKeyBoard and NumericalTextInput: https://forums.openpli.org/topic/60472-language-assistance-requested/

I am not an administrator so I can mark this issue as closed.  :)
