### ISSUE TITLE
Possibility to select stream port in settings

### ISSUE THREAD

**Issue by jmarquezt** [OpenPLi/enigma2#1832]
Port 8001 is in /lib/dvb/streamserver.cpp lines 307 and 310. Would it be possible to take the value from eConfigManager?

Thanks

**Comment by WanWizard** [comment]
Please ask support questions in our forum.

**Comment by Beaving** [comment]
I don't think this was a support request. He has the knowledge to change the port himself, but he was pointing out that those lines in streamserver.cpp uses a hardcoded value as port and he wants it to be configurable and get the port from eConfigManager.
