### ISSUE TITLE
lib/python/Components/config.py uses a non-existant variable.

### ISSUE THREAD

**Issue by original-birdman** [OpenPLi/enigma2#1844]
line 1447 is:

> if val is None and not locations:

however there is no `val`. This should be `sv`.
Clearly little used*, as it will crash if it ever is (which is how I found it in OpenVix).
OpenPLi is already correct. (*This code line doesn't seem to have changed in ~10 years)

**Comment by littlesat** [comment]
What is the issue... when you tell its fixed in openpli

**Comment by original-birdman** [comment]
It's also now in OpenVix: https://github.com/OpenViX/enigma2/pull/336
The symptom, if that function ever gets called, is an enigma2 crash. _e.g._:

> < 13016.108> Traceback (most recent call last):
> < 13016.108>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 51, in action
> < 13016.108>   File "/usr/lib/enigma2/python/Plugins/Extensions/NotifierTest/plugin.py", line 207, in keyFinish
> < 13016.110>     Setup.keyCancel(self)
> < 13016.110>   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 310, in keyCancel
> < 13016.111>   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 303, in closeMenuList
> < 13016.111>   File "/usr/lib/enigma2/python/Components/ConfigList.py", line 117, in isChanged
> < 13016.111>   File "/usr/lib/enigma2/python/Components/config.py", line 1649, in isChanged
> < 13016.112> NameError: global name 'val' is not defined

Also, just by looking at the code it is _clearly_ wrong. There is no `val`. By comparison with the other `isChanged()` functions it should be checking `sv`.

**Comment by ims21** [comment]
in any case, "val" not exists there...

**Comment by original-birdman** [comment]
> in any case, "val" not exists there...

Yes, that's what I'm saying - and fixing.

**Comment by littlesat** [comment]
How do you trigger it? i see you use a special trigger plugin or so. It can be there exist a plugin or code elsewhere that ‘includes’ the class and has the var...

**Comment by original-birdman** [comment]
Another developer wrote a test program to exercise the `config.py` code and this fell out as a result.

You can't "include" classes to make variables suddenly be declared - they are either declared in `config.py` or they do not exist: in this case `val` does not exist.

**Comment by Beaving** [comment]
Maybe make a pull request @original-birdman ? https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Components/config.py

**Comment by AbuBaniaz** [comment]
@original-birdman Can this be closed? Your fix was merged.

**Comment by original-birdman** [comment]
Yes. I'm closing it now....
