### ISSUE TITLE
Wrong color of subtitles in TV

### ISSUE THREAD

**Issue by kkm** [OpenPLi/enigma2#1958]
Hello,

Subtitle from automatically works great with auto color, but the red color is wrong, usually is white.
Can someone fix that or need raw clip from my country in Switzerland?

![](https://capturei.tikatoy.com/r/ztlv7dSraMeM.png)

kkm

**Comment by atvcaptain** [comment]
box model you have, possible drive issue

**Comment by kkm** [comment]
Vu+ Solo SE what is drive?

**Comment by WanWizard** [comment]
I'm not sure it is handy to have a discussion in two places.  We don't do issues on Github.

And this is perfectly normal, most German language channels use multi-colour subtitles, if you want all of them to be white, change it in the AV / subtitles settings.
