### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by technic** [OpenPLi/enigma2#1985]
[Clock is ticking](https://pythonclock.org/), are we planning to move to python 3.x?

**Comment by WanWizard** [comment]
No.

And I fear starting with it will open a big can of worms, the community out there still assumes all enigma2-based firmware is the same and interchangable, if the python version is changed immediately all binary ipk's floating around with only pyo's in them will no longer work...

/cc @eriksl @littlesat @athoik

**Comment by athoik** [comment]
Well python 2.7 will die hard...

Although it would be nice if new code is python3 compatible with unit testing.

Patches accepted ;)

**Comment by betacentauri** [comment]
https://docs.python.org/3/howto/pyporting.html

We should eg think about accepting new py files only if they use this:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

**Comment by betacentauri** [comment]
Just tested python-future on a sumo image. Sumo because python-future is there already included in the OE. It seems to work, but you need to use:
`from __future__ import print_function`

**Comment by betacentauri** [comment]
https://github.com/OpenPLi/enigma2/tree/python3

**Comment by technic** [comment]
The python files should be fine, I am more afraid about C-API part.

**Comment by athoik** [comment]
Maybe we can use enigma3 on the feeds!

That will allow to test enigma3 and speed up the whole process!

**Comment by betacentauri** [comment]
Swig seems to support python 3
http://www.swig.org/Doc1.3/Python.html#Python_python3support

But for testing I guess we first need to make main python files python 3 compatible.

**Comment by betacentauri** [comment]
Compiling e2 with python3 now works. But pyo/pyc files are missing in the package and more bad e2 don't work :-(
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named '_enigma'

**Comment by betacentauri** [comment]
The SWIG problems are solved. Changes are committed. 
There are still several issues with python code.

**Comment by athoik** [comment]
https://pythonclock.org/ sunset is close ..

**Comment by betacentauri** [comment]
Fortunately it won’t get fully dark at once. It’s similar to gstreamer 0.1 which we also used months/years after support had ended.

I see 2 major problems:
You can’t do it step by step. Means you cannot run parts of e2 with python2 and others with python3. And many plugins need to be adapted and no source and/or author is available.

**Comment by stevenhoving** [comment]
> And many plugins need to be adapted and no source and/or author is available.

Is there a list of these plugins?

**Comment by WanWizard** [comment]
There are two kinds of plugins:
- those for which source is publicly available. for these bitbake recipes exist, mainly plugins like https://github.com/OpenPLi/enigma2-plugins, https://github.com/e2openplugins and some from third party developers
- those for which no source is publically available, these are offered to users in our 3rd-party feed as a binary blob (ipk file). some contain source, some don't, some have a known author, some don't.  We have 320 of those online at the moment...

**Comment by technic** [comment]
We can try to use 2to3 for the available codebase and encourage plugin developers to use '__future__' imports in the code to make py2 code more compatible with py3

**Comment by athoik** [comment]
@technic there is already a hard work going on python3 branch.

Enigma2 is already usable for development. There are many plugins and a lot of nasty errors, but things moved a lot since 2019..

**Comment by AbuBaniaz** [comment]
As a python 3 OpenPLi image is out for testing, can we close this issue?

**Comment by WanWizard** [comment]
We will retire pyhon2 from next week.
