### ISSUE TITLE
AutoLanguageSelection does not work properly !

### ISSUE THREAD

**Issue by thawtes** [OpenPLi/enigma2#2022]
hello, AutoLanguageSelection does not work correctly on some channels.

when use AutoLanguageSelection, subtitle always showing !

I tried to explain with pictures !

![issue](http://666kb.com/i/e1evd4wroy3owkadl.png "screenshot")
![issue](http://666kb.com/i/e1evdfqfe5b9nrc7d.png "screenshot")
![issue](http://666kb.com/i/e1evdz2dhaeixs1vt.png "screenshot")
![issue](http://666kb.com/i/e1evj7fjitq4yqf7t.png "screenshot")

annoying :(  we have to turn off subtitles from the remote control

thanks

**Comment by WanWizard** [comment]
Please report issues in the forum, the issue tracker is not being used.

**Comment by thawtes** [comment]
> 
> 
> Please report issues in the forum, the issue tracker is not being used.

ok thx
