### ISSUE TITLE
FastScan west satellite position recognition

### ISSUE THREAD

**Issue by drsnacek** [OpenPLi/enigma2#2166]
Hello,

I can simulate new FST for UPC on Thore 0.8W. There is an issue in FST function there.

I setup Thor 0.8W on the first tuner. There are no other satellites on any port/tuner.

I add operator and Home TP to the FastScan plugin.py like:

('freeSAT CZ Thor 0.8W', (3, 82, False)),

(11727000, 28000000, eDVBFrontendParametersSatellite.FEC_7_8, 3592,
        eDVBFrontendParametersSatellite.Polarisation_Vertical, eDVBFrontendParametersSatellite.Inversion_Unknown,
        eDVBFrontendParametersSatellite.System_DVB_S, eDVBFrontendParametersSatellite.Modulation_QPSK,
        eDVBFrontendParametersSatellite.RollOff_alpha_0_35, eDVBFrontendParametersSatellite.Pilot_Off))

Unfortunately there is a bug in reading the west/east flag from the FNT table (flag ignored?)
FNT table itself checked by analyser and OK:

Descriptor: satellite_delivery_system_descriptor [0]: 0x43 (67)
+-descriptor_tag: 0x43 (67) => satellite_delivery_system_descriptor
+-descriptor_length: 0xB (11)
+-descriptor_data: 0x0117270000082102800005 "..'...!...."
+-frequency: 01172700 => 11.72700 GHz
+-orbital_position: 0008 => 0.8°
+-west_east_flag: 0x0 (0) => west
+-polarization: 0x1 (1) => linear - vertical
+-modulation_system: 0x0 (0) => DVB-S
+-modulation_type: 0x1 (1) => QPSK
+-symbol_rate: 0280000 => 28.0000 Msymbol/s
+-FEC_inner: 0x5 (5) => 7/8 conv. code rate

Enigma2 debug code:

[eDVBFrontend0] prepare_sat System 0 Freq 11727000 Pol 1 SR 28000000 INV 2 FEC 5 orbpos 3592 system 0 modulation 1 pilot 0, rolloff 0, is_id -1, pls_mode 1, pls_code 0
[eDVBFrontend0] tuning to 1127 mhz
[eDVBChannel] OURSTATE: tuning
[eDVBDemux] open demux /dev/dvb/adapter0/demux0
[eDVBSectionReader] DMX_SET_FILTER pid=83
[eDVBFrontend0] set static current limiting
[eDVBFrontend0] set sequence pos 3
[eDVBFrontend0] set sequence pos 4
[eDVBFrontend0] setVoltage 1
[eDVBFrontend0] sleep 200ms
[eDVBFrontend0] invalidate current switch params
[eDVBFrontend0] sendDiseqc: e00000(DiSEqC reset)
[eDVBFrontend0] sleep 50ms
[eDVBFrontend0] sendDiseqc: e00003(DiSEqC peripherial power on)
[eDVBFrontend0] sleep 150ms
[eDVBFrontend0] sendDiseqc: e01038f1(?)
[eDVBFrontend0] sleep 100ms
[eDVBFrontend0] set sequence pos 3
[eDVBFrontend0] setTone 1
[eDVBFrontend0] sleep 10ms
[eDVBFrontend0] update current switch params
[eDVBFrontend0] startTuneTimeout 5000
[eDVBFrontend0] setFrontend 1
[eDVBFrontend0] setting frontend
[eDVBFrontend0] fe event: status 0, inversion off, m_tuning 1
[eDVBFrontend0] sleep 500ms
[eDVBFrontend0] fe event: status 1f, inversion off, m_tuning 2
[eDVBChannel] OURSTATE: ok
[eDVBFrontend0] set dynamic current limiting
[eFastScan] servicesTableReady 0
[eDVBDemux] open demux /dev/dvb/adapter0/demux0
[eDVBSectionReader] DMX_SET_FILTER pid=82
[eFastScan] networkTableReady 0
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eFastScan] dropping this transponder, it's on another satellite 8 not configured.
[eDVBDB] Renumbering...
[eDVBDB] ---- saving lame channel db
[eDVBDB] saved 22 channels and 336 services!
[eDVBFrontend0] close frontend

**Comment by littlesat** [comment]
0.8 W vs 1.0 W ‘syndrome’?

**Comment by drsnacek** [comment]
FNT table:
orbital_position: 0008 => 0.8°
+-west_east_flag: 0x0 (0) => west

eDVBFrontend0:
orbpos 3592

eFastScan:
satellite 8 not configured

**Comment by ims21** [comment]
FreeSat does not broadcast Fastscan table yet. 
On 11727 is EPG for FreeSat and DigiTV only, no FastScan table.

**Comment by WanWizard** [comment]
What is the relation between the incorrect flag handing, Thor 0.8W, and FreeSat (which is on 28.2E)?

**Comment by ims21** [comment]
??? It is for me ? Btw - this log cannot be from our image. Tried it and no problem.

**Comment by WanWizard** [comment]
Yes, I didn't understand your "Freesat" remark...

**Comment by ims21** [comment]
Removed to your full satisfaction. Bye.

**Comment by WanWizard** [comment]
???

**Comment by ims21** [comment]
@WW - FYI - FreeSat is on 0.8W
@drsnacek - may be, if you simulate it you have not configured 0.8W in e2? Then is automaticaly this all from this satelite dropped out in FS ([here](https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/fastscan.cpp#L490)). You can disable it in FS config.
- but FreeSat not broadcasting FS table. There on this transponder is EPG only. May be, when M7 bought it, there will be in future, but as they told - "a lot of work with absorbtion FreeSat by M7".

**Comment by WanWizard** [comment]
Ok, clear. Didn't get that. Confusing, two providers, both called "FreeSat", on two different sats...

**Comment by drsnacek** [comment]
@ims21 - I have configured 0.8W on the tuner. When I disabled the check in FS config. So I got the list of channels from the simulated FastScan but all of them have 0.8E instead of the expected 0.8W. The FastScan itself has been checked by the analyser and contains 0.8W info. So it looks like the West flag is not read from FastScan table properly...
To be sure I made a script to change the 0.8E in the lamedb file to 0.8W. Then All channels started to play.

**Comment by ims21** [comment]
Try add to end of this line https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/fastscan.cpp#L488 this:
` + ((orbitalposbcd >> 12) & 0x0f) * 1000;`

**Comment by drsnacek** [comment]
The UPC FastScan is on Thor 0.8W now. So you can test...

**Comment by ims21** [comment]
How do you know, that M7 started broadcasting fastscan table on 0.8W ? Do you know parameters ?

**Comment by ims21** [comment]
It seems, there in Fastcan really is not used west_east_flag
Then all orbital positions will be as east always.

**Comment by ims21** [comment]
Found. I will create patch soon

**Comment by WanWizard** [comment]
Patches merged into the develop branch.

**Comment by ims21** [comment]
Could be it added to 7.1 too ? I think, for us it is quite important.
Thx.

**Comment by WanWizard** [comment]
If the tests in the develop build don't show up any issues, I'll cherry pick later this week.

**Comment by littlesat** [comment]
please 🍒 pick

**Comment by ims21** [comment]
It is in 7.1 yet

**Comment by AbuBaniaz** [comment]
I thought this issue was fixed. If so, can issue be closed?

**Comment by WanWizard** [comment]
Quite possible, I don't think anyone folllows up github issues...

**Comment by ims21** [comment]
I fixed it cca 2months ago
