### ISSUE TITLE
Improvement: spinner during harddisk startup

### ISSUE THREAD

**Issue by dAF2000** [OpenPLi/enigma2#2285]
If you set your harddisk to idle (spin down) automatically after a few minutes, the "busy spinner" doesn't show directly if you access the harddisk (timeshift, movie list etc). The harddisk spin up may take a few seconds so users may think the receiver didn't react on the remote control. An immediate feedback (busy spinner) is needed here.

I know the spinner only shows if Enigma is blocked someway. But if we can manually start the spinner this would be possible:

- start spinner
- fopen("harddisk") or whatever access to the harddisk which could block Enigma.
- stop spinner

If one uses a NAS, the delay may be even larger and more annoying without spinner feedback.

https://forums.openpli.org/topic/70722-improvement-spinner-during-harddisk-startup/

**Comment by littlesat** [comment]
Issue is solved... the please wait message now always appear first. When it takes longer the spinner also pop-ups.
