### ISSUE TITLE
Opinions on string renaming

### ISSUE THREAD

**Issue by nautilus7** [OpenPLi/enigma2#2380]
@WanWizard or anyone who cares, I consider changing all "Picture in Picture" instances to "PiP". Currently there is a mix of both with the full string used in 6 occasions, while the abbreviation is used in 25 occasions. There is also a"PIP" version used in a couple of instances.

What do you think? Should I renamed all of them to just "PiP"? I could keep "Picture in Picture" in some cases if it feels better (I'll see). Or should I just rename the nasty "PIP" to "PiP" and get done with it?

Existing translations will be kept, of course.

**Comment by WanWizard** [comment]
Mixed feelings, I am not sure every "average user" knows what PiP means? And there are probably locations where "Picture in Picture" as a string is too long.

**Comment by littlesat** [comment]
Call all of them PiP except for longer descriptions you should call it Picture in Picture...

**Comment by nautilus7** [comment]
For now I made some tweaks in some stings. https://github.com/nautilus7/enigma2/commit/21aaafee1251c5d88c4bff74b5c5d4948ac43adc

I changed "PIP" to "PiP" and "PiP" to "Picture in Picture" in some longer descriptions and messagebox texts, as littlesat suggested. I didn't shorten "Picture in Picture" to "PiP" in other occasions though.

I also tweaked some strings in "setup.xml" in other aspects. Please comment on these. Thanks.

**Comment by WanWizard** [comment]
@littlesat ?
