### ISSUE TITLE
Some leftover /usr/lib/... hard-coded paths - Can these be fixed?

### ISSUE THREAD

**Issue by nautilus7** [OpenPLi/enigma2#2416]
I am trying to eliminate all `/usr/lib` hard-coded paths from enigma2, so it is compatible with multi lib images (that support 64bit and 32bit binaries and executables and have both `/usr/lib/` and `usr/lib64` directories).

I [fixed several of them](https://github.com/OpenPLi/enigma2/commit/b6de676dab8dab1720e9c32fdb820cadecbb7320) yesterday, but there are 3 cases left with such hard-coded paths:

1. https://github.com/OpenPLi/enigma2/blob/develop/mytest.py#L3 I have no clue what this is and how to fix it. I guess this is not that important for eveyday use. It was added with this commit https://github.com/OpenPLi/enigma2/commit/0e003cd9c9f2f15261eb81d374f99454637a1442

2. https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Components/About.py#L14 I think that ipkg is obsolete and the whole "else" clause can be removed together with the path. So, it seems trivial to fix.

3. https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Plugins/Extensions/TuxboxPlugins/plugin.py#L9 What is this plugin? Is it still used or it's a leftover piece from old code? [Modification history](https://github.com/OpenPLi/enigma2/commits/develop/lib/python/Plugins/Extensions/TuxboxPlugins/plugin.py) of this file seems ancient...

**Comment by WanWizard** [comment]
1. @littlesat ?

1. ipkg is indeed obsolute, the else can be  removed.

1. I think this link is wrong?  Other than that, I did some Googling, and I can only find references to cdk images (Enigma1).

**Comment by nautilus7** [comment]
@WanWizard sorry, link in case 3 fixed.

**Comment by WanWizard** [comment]
Thanks. 

Perhaps @littlesat knows more about the background, but in my 14 years PLi I've never seen an E2 Tuxbox plugin, so no idea why that is still there...

**Comment by nautilus7** [comment]
Yep, same here in my 8 years of using openpli/satdreamgr.

**Comment by AbuBaniaz** [comment]
Does this help?
https://github.com/OpenVisionE2/enigma2-openvision/commit/d876625d80d1fba22768c3465858747a1df30fcc

**Comment by nautilus7** [comment]
SCOPE_LIBDIR would be a nice addition and a useful tool in some cases. Thanks.

**Comment by AbuBaniaz** [comment]
Pull request raised by @persianpros 
https://github.com/OpenPLi/enigma2/pull/2421/files

**Comment by persianpros** [comment]
I think it's safe to remove the ancient code :+1: 

It's develop branch so we could test it.

**Comment by WanWizard** [comment]
Agreed.

**Comment by AbuBaniaz** [comment]
Tuxbox was in E1 and Neutrino. There is an E2 version that the Beyonwiz team have. ATV have adopted it. I think it's been discussed on forum (not 100% sure though)

**Comment by persianpros** [comment]
Seems ATV has ancient too: https://github.com/openatv/enigma2/tree/6.3/lib/python/Plugins/Extensions/TuxboxPlugins

History: https://github.com/openatv/enigma2/commits/6.3/lib/python/Plugins/Extensions/TuxboxPlugins

**Comment by AbuBaniaz** [comment]
Not that one, so it can be removed once someone confirms it's ok. The new one is tuxbox commander

**Comment by persianpros** [comment]
PR: https://github.com/OpenPLi/enigma2/pull/2423

**Comment by nautilus7** [comment]
I suppose this can be closed now. Thanks.
