### ISSUE TITLE
Proposal for combining the recording options/setup in a single menu entry

### ISSUE THREAD

**Issue by nautilus7** [OpenPLi/enigma2#2445]
In the menu there is the [recording](https://github.com/OpenPLi/enigma2/blob/develop/data/menu.xml#L61) setup from [setup.xml](https://github.com/OpenPLi/enigma2/blob/develop/data/setup.xml#L147) and also the [recording paths](https://github.com/OpenPLi/enigma2/blob/develop/data/menu.xml#L73) from the [respective screen](https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Screens/RecordPaths.py).

What would you think if I combine the options from the two in a single screen and use a single entry in the menu; It is common sense to have all related options together and this is what other images do.

Opinions?

**Comment by AbuBaniaz** [comment]
Good idea IMO.

Only complication is that some options were meant to be dependent to being in expert mode, but I am sure you will deal with those.
