### ISSUE TITLE
Skin issue with include syntax

### ISSUE THREAD

**Issue by athoik** [OpenPLi/enigma2#2525]
@IanSav,

A user reported on SatDreamGr that attached skin is not working properly.

There is no "skin_user.xml" included on this skin as I noticed.

Any idea what is going wrong, can you please have a look?

[enigma2-plugin-skins-bardo-fhd_1.2_all.zip](https://files.fm/f/4kbnvd7b)

**Comment by atvcaptain** [comment]
@athoik i test the skin with atv 6.4 and new skin engine, works fine all ok here

**Comment by IanSav** [comment]
What is the nature of the issue?  Can you please give me some more information with which to test for the problem.

Also, I have an updated skin engine for OpenPLi.  It is already on OpenViX and a derivative is running on OpenATV.  It may help to address this and any other load sequence issues.  I will prepare an update ASAP.

**Comment by athoik** [comment]
The main menu is wrong (it shows main menu from skin_default with other colours i think).

**Comment by IanSav** [comment]
Is it possible to have a screen capture to show how the menu screen should look.

This is what I see:
![Menu](https://user-images.githubusercontent.com/6904736/79064129-ad9a0d80-7ce9-11ea-8ce8-2b69ec9c5243.jpg)

**Comment by athoik** [comment]
This is how it should look like: https://i.postimg.cc/rwQwQYzy/menu.jpg

**Comment by IanSav** [comment]
Wow, that is very different!

**Comment by IanSav** [comment]
This skin uses custom plugins and renderers.  Has all this other code been checked?

**Comment by IanSav** [comment]
I have found the problem.  The skin is not defining the screen "menu_mainmenu" so the system is loading the "menu_mainmenu" screen from the emergency skin.

If this skin wishes to replace "menu_mainmenu" it needs to define this screen within the skin.

This is NOT a skin.py code problem.

**Comment by IanSav** [comment]
Can this issue now be closed.

**Comment by athoik** [comment]
Sure, I hope the skin author to be noticed in order to update his skin (don't know how to notify him).
