### ISSUE TITLE
HDMI-CEC SystemPlugin Forward volume keys doesn't work anymore

### ISSUE THREAD

**Issue by LittleJoe-CH** [OpenPLi/enigma2#2589]
Hi team,

I've compiled my own develop build for zgemma h9 (h9.2s) because I wanted to include the 2 USB serial drivers FTDI_SIO and IUU_PHOENIX within the kernel. Everything is perfect but with HDMI-CEC I cannot forward my remote control volume keys to my ONKYO receiver anymore (Compared to the official 7.2 release which works well with this option.)

At your disposal to help debug and fix this issue.

Thanks.
LittleJoe (CH)

**Comment by WanWizard** [comment]
As far as I can see, nothing has changed to Enigmas CEC layer, perhaps a driver issue?

There was a driver update recently: https://github.com/zgemma-star/meta-zgemma/commit/fbbd03d3e1175fcef210e669d2b2a6486ef6b6bb#diff-d65ac1543f8cde1d3a0b5722c1053215

**Comment by LittleJoe-CH** [comment]
Updated meta-zgemma. Everything OK. Thanks!
