### ISSUE TITLE
HDMI-CEC problems

### ISSUE THREAD

**Issue by ToxicLand** [OpenPLi/enigma2#2684]
Issues persist on Solo 4K and Zero 4K:

1. Forward volume keys stops working after an enigma2 restart. Only a box reboot fixes the problem.
2. When CEC is enabled on the box, it will not switch the soundbar to ARC source.

**Comment by WanWizard** [comment]
CEC has always been hit and miss with a VU+, which is unfortunately handled at driver level. The only thing you can control in software is timing.
