### ISSUE TITLE
21:9 content appears as 'stretch nonlinear'

### ISSUE THREAD

**Issue by ToxicLand** [OpenPLi/enigma2#2695]
So far I only noticed this issue on 0.8W 11843V 30000, with HBO HD. When the channel broadcasts >16:9 content, sometimes it appears as 'stretch nonlinear' even if my setting is 'letterbox'. I have to switch to another setting, then back to 'letterbox' to fix it. The issue appears again after a reboot. Video of the issue: https://streamable.com/w2ppp0 (although the video was taken on ATV, it happens on PLI too since a few months.)

**Comment by WanWizard** [comment]
It has to be reported to the manufacturer of your receiver, as this is dealt with in the drivers.

**Comment by ToxicLand** [comment]
That means it is never going to be fixed just like the Dolby no sound issue (Vu+ Solo 4K) and HDMI CEC. Thanks though.

**Comment by WanWizard** [comment]
If you can report it on the forum, as specific as possible (also the Dolby issue), and if possible with examples, we can try to use our contacts to push VU+.

**Comment by ToxicLand** [comment]
https://forums.openpli.org/topic/78022-219-content-appears-as-stretch-nonlinear/
