### ISSUE TITLE
Missing Entries for old JULTEC Matrix

### ISSUE THREAD

**Issue by muech011** [OpenPLi/enigma2#2745]
Old JULTEC Matrix (e.g. JPS0501-8 (A/M/T)) are not supported in the tuner setups. Most of the distributions supports them but it's missing in OpenPLI and TeamBlue.

**Comment by WanWizard** [comment]
OpenPLi uses generic entries instead of a very, very long list of all possible switch names.

The JPS05010-8 has 8 user bands, so you need to select "JPSxx/JRSxx 8 UB" which is a generic entry for all Jultec switches supporting 8 user bands.

**Comment by muech011** [comment]
Sorry, but the Frequencies used for "JPSxx/JRSxx 8 UB" do not match the frequencies used by the "old" JULTEC devices. So it can't be used.

**Comment by WanWizard** [comment]
Please report this in the forum, so someone can update it. None of the developers check github.

**Comment by littlesat** [comment]
Can you give me the frequencies for this device?

**Comment by WanWizard** [comment]
ATV has
````
<product name="JPS0501-8(A/M/T)"   format="JESS" scr1="1076" scr2="1178" scr3="1280" scr4="1382" scr5="1484" scr6="1586" scr7="1688" scr8="1790"/>
````
