### ISSUE TITLE
Error compile enigma2.

### ISSUE THREAD

**Issue by 68foxboris** [OpenPLi/enigma2#2825]
Maybe it's just me, but the compilation error is enigma2. And a lot of errors Warning 503: Can't wrap 'operator 

`
depbase=`echo base/eenv.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
arm-oe-linux-gnueabi-g++  -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a15 --sysroot=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/lib -I..  -I.. -I../../git -I../../git/include -include Python.h -include ../enigma2_config.h -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/python2.7  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wall -Werror 						-Warray-bounds=1 						-I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/freetype2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/fribidi -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libpng16 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libxml2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/sigc++-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/sigc++-2.0/include -fno-rtti -fno-exceptions -rdynamic -funwind-tables -pthread -fopenmp  -MT base/eenv.o -MD -MP -MF $depbase.Tpo -c -o base/eenv.o base/eenv.cpp &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo base/eerror.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
arm-oe-linux-gnueabi-g++  -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a15 --sysroot=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/lib -I..  -I.. -I../../git -I../../git/include -include Python.h -include ../enigma2_config.h -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/python2.7  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wall -Werror 						-Warray-bounds=1 						-I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/freetype2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/fribidi -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libpng16 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libxml2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/sigc++-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/sigc++-2.0/include -fno-rtti -fno-exceptions -rdynamic -funwind-tables -pthread -fopenmp  -MT base/eerror.o -MD -MP -MF $depbase.Tpo -c -o base/eerror.o ../../git/lib/base/eerror.cpp &&\
mv -f $depbase.Tpo $depbase.Po
../../git/lib/base/smartptr.h:64: Warning 503: Can't wrap 'operator eWindowStyle*' unless renamed to a valid identifier.
../../git/lib/base/smartptr.h:64: Warning 503: Can't wrap 'operator eWindowStyleManager*' unless renamed to a valid identifier.
depbase=`echo base/elock.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
arm-oe-linux-gnueabi-g++  -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a15 --sysroot=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/lib -I..  -I.. -I../../git -I../../git/include -include Python.h -include ../enigma2_config.h -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/python2.7  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wall -Werror 						-Warray-bounds=1 						-I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/freetype2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/fribidi -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libpng16 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libxml2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/sigc++-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/sigc++-2.0/include -fno-rtti -fno-exceptions -rdynamic -funwind-tables -pthread -fopenmp  -MT base/elock.o -MD -MP -MF $depbase.Tpo -c -o base/elock.o ../../git/lib/base/elock.cpp &&\
mv -f $depbase.Tpo $depbase.Po
../../git/lib/base/smartptr.h:64: Warning 503: Can't wrap 'operator eActionMap*' unless renamed to a valid identifier.
../../git/lib/base/eerror.cpp: In function 'void eDebugImpl(int, const char*, ...)':
../../git/lib/base/eerror.cpp:166:18: error: unused variable 'tp' [-Werror=unused-variable]
  166 |  struct timespec tp;
      |                  ^~
depbase=`echo base/encoding.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
arm-oe-linux-gnueabi-g++  -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a15 --sysroot=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/lib -I..  -I.. -I../../git -I../../git/include -include Python.h -include ../enigma2_config.h -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/python2.7  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0=/usr/src/debug/enigma2/2.7+gitAUTOINC+d6c5244c73-r0                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -Wall -Werror 						-Warray-bounds=1 						-I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/freetype2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/fribidi -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/glib-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libpng16 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/libxml2 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/include/sigc++-2.0 -I/home/foxbob/et/openpli-oe-core/build/tmp/work/et1x000-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+d6c5244c73-r0/recipe-sysroot/usr/lib/sigc++-2.0/include -fno-rtti -fno-exceptions -rdynamic -funwind-tables -pthread -fopenmp  -MT base/encoding.o -MD -MP -MF $depbase.Tpo -c -o base/encoding.o ../../git/lib/base/encoding.cpp &&\
mv -f $depbase.Tpo $depbase.Po
cc1plus: all warnings being treated as errors
make[4]: *** [Makefile:1845: base/eerror.o] Error 1
make[4]: *** Waiting for unfinished jobs....
`

[log.do_compile.zip](https://github.com/OpenPLi/enigma2/files/5744598/log.do_compile.zip)

**Comment by WanWizard** [comment]
Is a work-in-progress. 

Now that the release is branched off, all error reporting has been enabled so we can get rid of all sorts of vague and hidden errors in Enigma. It's develop, it isn't always stable... :grin:

**Comment by 68foxboris** [comment]
Compilation was successful with these parameters
`
  diff --git a/configure.ac b/configure.ac
  index c6ab668..dca797c 100644
   --- a/configure.ac
   +++ b/configure.ac
   @@ -248,6 +248,11 @@ CFLAGS="$CFLAGS -Wall"
    CXXFLAGS="$CXXFLAGS -Wall -Werror \
   						-Wno-error=stringop-truncation \
   						-Warray-bounds=1 \
     +						-Wno-error=unused-variable \
     +						-Wno-error=sign-compare \
     +						-Wno-error=reorder \
     +						-Wno-error=deprecated-declarations \
     +						-Wno-error=format-zero-length \
   						$BASE_CFLAGS $ENIGMA2_CFLAGS $PTHREAD_CFLAGS $OPENMP_CFLAGS 
   $ALSA_CFLAGS"
   
   AC_CONFIG_FILES([
`

**Comment by WanWizard** [comment]
We are aware of that. The point of this excercise is not to hide or suppress the errors, but to find and fix them.

**Comment by 68foxboris** [comment]
Clear.
