### ISSUE TITLE
EPG on 28.2° missing data

### ISSUE THREAD

**Issue by willow5** [OpenPLi/enigma2#2922]
Hi, I have been directed here by betacentauri from the openatv forum. I have an issue with the openatv epg on 28.2° where it is missing data on many channels, see attachment. Can you help please?
![1_0_19_22D9_80D_2_11A0000_0_0_0_20210410125207](https://user-images.githubusercontent.com/64496221/114271769-09859800-9a0b-11eb-9b28-27a25cfa3bd7.jpg)

**Comment by LraiZer** [comment]
> The ones that have populated themselves have done so with Freesat epg. The others with no epg are not from the Freesat provider, they are from the Sky provider.
> 
> You need to zap to "IEPG data 1" at least daily to update the epg channels that have not populate themselves.
> Most users install a plugin called "EPG Refresh" and set it to wake up and zap to this channel for 3 minutes while they are asleep.

See [comment thread](https://github.com/OpenPLi/enigma2/pull/2920#issuecomment-817283879)

Issue can be closed.
