### ISSUE TITLE
Frame by frame advance for mpg files

### ISSUE THREAD

**Issue by willow5** [OpenPLi/enigma2#2930]
Is it possible to have a frame by frame advance for mpg files? I cannot seem to even forward or rewind in slow motion with mpg files in pause mode, is this a glitch?

**Comment by WanWizard** [comment]
That depends on the file. 

Winding is basically a skip from I-frame to the next I-frame, as you need full frames to be able to display something, and depending on the encoding of the file, the interval between two of those frames might be too long (file too much compressed). Implementation is in the drivers, so if it doesn't work, the manufacturer needs to fix it.
