### ISSUE TITLE
HLS player

### ISSUE THREAD

**Issue by willow5** [OpenPLi/enigma2#2980]
I am struggling to get my receiver to play a HLS AES encrypted stream which contains the following key inside the extm3u file:

#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://1234556788=",KEYFORMAT="com.apple.streamingkeydelivery",IV=0x00000000000000000000000000000000

The receiver constantly restarts using player 4097 and does nothing using 5001 and 5002.

Any advice or plugins available to remedy this ? The file plays fine on a PC

**Comment by WanWizard** [comment]
Please report it in the forum, nobody checks these issues... They'll probably need a working URL to test.

**Comment by willow5** [comment]
sure, which forum is this ? I am running openatv....or should I report to the Pli forum ?

**Comment by WanWizard** [comment]
Why do you report a problem to OpenPLi if you are not using it?
