### ISSUE TITLE
rc_models.cfg

### ISSUE THREAD

**Issue by miraclebox-git** [OpenPLi/enigma2#320]
Hello,

We noticed that there was some problem with merge one of the files

data/rc_models/rc_models.cfg

the entry:

7000S miraclebox

should be changed to

7000S miraclebox2

Thanks

**Comment by WanWizard** [comment]
Has been adressed in https://github.com/OpenPLi/enigma2/commit/53562a4d04ca2b43df5a480bf7c135661f45b077
