### ISSUE TITLE
Python 3 or OE 2.5?

### ISSUE THREAD

**Issue by Melgas** [OpenPLi/enigma2#3269]
Hi,

I have a DM920-4K UHD, with an OE2.5 Image installed.

There is no OE2.5 Image, with Python 3. Only in OE2.0 Images, we find PY3.

Please, I come to ask you to inform me:

1. Is there an advantage in installing an Image with Python 3.9?

2. Or are OE2.5 Images with PY2 equivalent to those with PY3?

Thanks.

**Comment by WanWizard** [comment]
We don't use this issue tracker. Also, we don't make images for a DM920.
