### ISSUE TITLE
Press record button in single or multi EPG to schedule a selected program

### ISSUE THREAD

**Issue by klorinczi** [OpenPLi/enigma2#3385]
I would like to press record button in single or multi EPG to schedule a selected program.

This would make much easier the record scheduling.

Should work like this:
Open single or multi EPG / move cursor to a program / press Record button to select the program for recording.

No pop-up, no editable options, just save the selected program for scheduled recording.

This would make record scheduling very easy.
Thanks!

**Comment by ims21** [comment]
why next function, when you can in any EPG press "green" and "OK" for recording ?

**Comment by klorinczi** [comment]
Why doing 2 button presses, when user could just press 1 record button?

We could just save a button press and avoid accidentally change the recording filename.

**Comment by WanWizard** [comment]
I don't really see the added value, it's not that you plan 500 recordings a day...

**Comment by klorinczi** [comment]
Again: why press 2 buttons, when only 1 button press would be enough?

**Comment by WanWizard** [comment]
Because by that argument alone, your remote should have 500 buttons.

**Comment by klorinczi** [comment]
Technisat receivers are working this way. 

I found the feature useful to press Record button on a selected EPG item and schedule it to be recorded.

This does not require new button, just a Record button shortcut on EPG screen to schedule recording the selected show in a simple way, without any intermediate screens.
