### ISSUE TITLE
Timer List (Content/description of a timer is not displayed correctly)

### ISSUE THREAD

**Issue by Astro-Martin** [OpenPLi/enigma2#3392]
Menu -> Timer
If you switch from one entry directly to another entry, the display on the left side is updated.

Fast scrolling through the list of timers does not update the display on the left.

**Comment by WanWizard** [comment]
When you scroll it generates events to update the description, but events are fired faster than the system can update, so you lose events. With a bit of bad luck you lose the last one, meaning the final display is incorrect.

This is inherent to the async nature of a realtime application (both functions run independently), and not easy to solve.
