### ISSUE TITLE
Fix SNR for rs6060

### ISSUE THREAD

**Issue by popking159** [OpenPLi/enigma2#3754]
Please add fix for SNR to rs6060 in frontend.cpp .
Thanks in advance

**Comment by WanWizard** [comment]
Please ask in the forum, this issue tracker isn't used.

**Comment by AbuBaniaz** [comment]
This was added in March here:
https://github.com/OpenPLi/enigma2/commit/a9f0b3ff5d902461f8d4876b6925f0a59041d1ae

Issue can be closed
