### ISSUE TITLE
CI+ menu/text is not rendered if CI+ provides the encoding into the menu/text item

### ISSUE THREAD

**Issue by madface2000** [OpenPLi/enigma2#3821]
Some of the CI+ cards are providing the encoding required to display menu/text items.
For example, 0x9F, 0x88, 0x03, 0x0E, 0x10, 0x00, 0x02, 0x44, 0x69, 0x61, 0x67, 0x6E, 0x6F, 0x73, 0x74, 0x69, 0x63, 0x73, will represent "Diagnostics" with ISO8859-2 encoding (0x10, 0x00, 0x02 in the array above), where:

- first 3 bytes are tags sent by CI+
- 4th byte is the length of the array (including the encoding part 0x10, 0x00, 0x02)
- from 5th byte, the array conatins the encoding and the actual text.

When mmiScreenEnq or mmiScreenAddText is called, they will pass to convertDVBUTF8 function, 0x10, 0x00, 0x02, 0x44, 0x69, 0x61, 0x67, 0x6E, 0x6F, 0x73, 0x74, 0x69, 0x63, 0x73, '\0' as string. Because the second byte is 00, the encoding cannot be determined and also the presumed converted string will be null.

Instead of using:

`mmiScreenEnq(slot_id, blind, alen, (char*)convertDVBUTF8(str).c_str());      //mmi_ui.cpp:80`
and
`mmiScreenAddText(slot_id, pos++, (char*)convertDVBUTF8(str).c_str());      //mmi_ui.cpp:116`

a better way would be to use:

`mmiScreenEnq(slot_id, blind, alen, (char*)convertDVBUTF8((const unsigned char*)str, textlen,-1, 1, 0).c_str());`
and
`mmiScreenAddText(slot_id, pos++, (char*)convertDVBUTF8((const unsigned char*)str, textlen,-1, 1, 0).c_str());`

This will work either for:
{0x9F, 0x88, 0x03, 0x0E, 0x10, 0x00, 0x02, 0x44, 0x69, 0x61, 0x67, 0x6E, 0x6F, 0x73, 0x74, 0x69, 0x63, 0x73} or for
{0x9f, 0x88, 0x03, 0x0B, 0x44, 0x69, 0x61, 0x67, 0x6E, 0x6F, 0x73, 0x74, 0x69, 0x63, 0x73}

Sorry for the above syntax (constant values for parameters passed to convertDVBUTF8), but I am not a good C++ programmer....

**Comment by WanWizard** [comment]
@Dima73 @ims21 ?

**Comment by betacentauri** [comment]
I try to take a look at it. But it will take some time. If someone is faster, be so kind and fix it.
By the way the encoding is described in EN 300 468 annex A.2. First byte < 0x20 means non latin alphabet. 0x10 like in the example above is special as then 3 bytes encode the character set otherwise only 1 byte (quite strange...).

**Comment by betacentauri** [comment]
@madface2000  Can you post an e2 debug log with log level 5?
ENIGMA_DEBUG_LVL=5 enigma2 > /tmp/log.txt 2>&1

Looking at the code I see no issues.
https://github.com/OpenPLi/enigma2/blob/develop/lib/base/estring.cpp#L607  -> looks for 0x10 
https://github.com/OpenPLi/enigma2/blob/develop/lib/base/estring.cpp#L611  -> next 2 bytes (in your case 0x00, 0x02) are read 
-> From position i (i is after 0x10,0x00,0x02) all character will be converted.
At least it looks like

**Comment by madface2000** [comment]
@betacentauri I will provide a debug log with level 5. Please bear with me. I have to flash back the original image. Currently I am using a patched one where I changed the code as I mentioned in the beginning and is working.

The problem is not in the estring.cpp code. All is good there!
The problem is with the way convertDVBUTF8 is called from mmiScreenEnq or mmiScreenAddText. Both are using this prototype:
```

inline std::string convertDVBUTF8(const std::string &string, int table=-1, int tsidonid=1,int *pconvertedLen=0)
{
	return convertDVBUTF8((const unsigned char*)string.c_str(), string.length(), table, tsidonid,pconvertedLen);
}
```
Above lines are in estring.h

Both (mmiScreenEnq or mmiScreenAddText) are passing the address of string, so when the string is picked up in  convertDVBUTF8, it will be truncated and will have only 0x10... (my guess)

I will provide also the debug within the next couple of days.

Thank you!

**Comment by betacentauri** [comment]
Didn't recognize that inline function. So there is an implicit conversation from char* to string. That will remove all behind the 0x0.  You're right. Good catch!

**Comment by madface2000** [comment]
> Didn't recognize that inline function. So there is an implicit conversation from char* to string. That will remove all behind the 0x0. You're right. Good catch!

@betacentauri Do you still need the debug log?

**Comment by betacentauri** [comment]
No. Will push a fix in a few minutes.

**Comment by betacentauri** [comment]
https://github.com/OpenPLi/enigma2/commit/6ff82d574e4b121a55be38f4f2e2925842589632

**Comment by WanWizard** [comment]
Brillant find, thanks @madface2000  ! :+1:

**Comment by madface2000** [comment]
You are welcome! Thank you too, for fixing this in no time!
