### ISSUE TITLE
Vu+ Solo2 Tuner loop-through not available

### ISSUE THREAD

**Issue by jbollacke** [OpenPLi/enigma2#3828]
There is no option to loop-through tuner a to tuner b (again).

I thought this was fixed with #3107 . But it looks like it was overwritten with: https://github.com/OpenPLi/enigma2/commit/6c1aa22044757da788cf2b88589f611884e34289

OpenPLi version: 9.0 (3.9+git20894+c315ed5)

**Comment by WanWizard** [comment]
The hardware doesn't loop A to B, it loops B to A. 

Previously you needed a plugin to hack this in, but it did it the other way rond. This is no longer needed, the software follows the hardware. So if you have only one cable, connect it to B, and then configure A loop through from B.

**Comment by jbollacke** [comment]
Whoops! Did not test it this way... TY

**Comment by WanWizard** [comment]
I didn't know either, but the same issue was reported earlier this week in the Dutch section of our forum.
