### ISSUE TITLE
Revert work-a-round when certificate issue in OE is solved

### ISSUE THREAD

**Issue by littlesat** [OpenPLi/enigma2#411]

**Comment by athoik** [comment]
I think the certificate now work in latest images, maybe we need to revert the workaround?

**Comment by WanWizard** [comment]
Not sure what "certificate issue" exactly is, but the current image has no issues with https and certificates.

**Comment by WanWizard** [comment]
Not sure this can be closed, I'm pretty sure the old "OpenPLi 4" workaround  (i.e. do not check the certificate) is still present in the codebase. @littlesat ?
