### ISSUE TITLE
Support Multistream

### ISSUE THREAD

**Issue by athoik** [OpenPLi/enigma2#421]
- [x] Add drivers for Multistream capable devices like TBS
- [x] Get MIS/PLS changes from @crazycat69 (https://github.com/crazycat69/openpliPC)
- [x] Allow NimManager to query frontend if has multistream cabability
  - [x] Add workaround due to poor support for VTUNER_SET_FE_INFO
- [x] Display MIS/PLS only when NIM is multistream
- [x] Support saving lamedb and lamedb5 only when Multistream values exist
- [x] Wait until channel editors add support for MIS/PLS
- [x] Fix auto DiSEqC
- [x] Use S2_SATELLITE_DELIVERY_SYSTEM_DESCRIPTOR
- [x] Merge when OpenPLi 5 released
  - [x] Fix Blindscan missing is_id/pls_mode/pls_code after merging Multistream support

Multistream work in progress: https://github.com/athoik/enigma2/tree/multistream

**Comment by AbuBaniaz** [comment]
Shouldn't this issue be closed?

**Comment by athoik** [comment]
Almost, the S2 descriptor is still missing.

**Comment by athoik** [comment]
S2_SATELLITE_DELIVERY_SYSTEM_DESCRIPTOR added via https://github.com/OpenPLi/enigma2/commit/9d801909af28d4d04550df92da507bc9b679e297

Now we have to fine tune it by removing Root and Combo modes and accept only Gold sequences, since those sequences are the ones that EN 300 468 table 41 uses.
