### ISSUE TITLE
Solve bitrate viewer issues for e.g. HD51

### ISSUE THREAD

**Issue by littlesat** [OpenPLi/enigma2#423]

**Comment by athoik** [comment]
The problem is that you cannot start PES filter on video PID.  Sounds like driver issue.

You can test it with dvbsnoop. Same happens on VuSolo4k!

As a workaround there is an option on bitrate viewer (`#define`) to use TS filter.

**Comment by littlesat** [comment]
Do you have any idea how to switch it to TS filter As far I can see it is somehow prepared for it...... Probably (as work-a-round) we can consider to change it to TS filter.

Of course it might be helpfull to have PES filter on HD51/Solo4K

**Comment by athoik** [comment]
I tried to change bitrate to TS mode. It doesn't work 

```c
diff --git a/bitratetool/bitrate.cpp b/bitratetool/bitrate.cpp
index e1c5159..7cc697d 100644
--- a/bitratetool/bitrate.cpp
+++ b/bitratetool/bitrate.cpp
@@ -11,7 +11,7 @@
 #include <iostream>
 #include <vector>

-/* #define USE_TS_FILTER */
+#define USE_TS_FILTER

 #ifdef USE_TS_FILTER
 # define TS_LEN       188
@@ -133,15 +133,16 @@ int measureBitrate(int adapter, int demux, bool oneshot, std::vector<int> pids)
                ::ioctl(fd, DMX_SET_BUFFER_SIZE, 1024 * 1024);
                dmx_pes_filter_params flt;
 #ifdef USE_TS_FILTER
-               flt.pes_type = 0; /* officially not allowed, but on systems with ADD_PID support, this results in TS data */
+               flt.pes_type = (dmx_pes_type_t)0; /* officially not allowed, but on systems with ADD_PID support, this results in TS data */
 #else
                flt.pes_type = DMX_PES_OTHER; /* PES payload data */
 #endif
```

Don't know why but PES on Video PID simply doesn't work.

**Comment by littlesat** [comment]
Can you try to switch to TS> does it has effect on other hardware?

**Comment by athoik** [comment]
Here is the bitrate tool compiled for mipsel with above changes. 

[bitrate.zip](https://github.com/OpenPLi/enigma2/files/473339/bitrate.zip)

On arm it didn't work. I can't test right now on mipsel, so give a try.

**Comment by Dima73** [comment]
So there is a arm problem solution?

**Comment by athoik** [comment]
It seems VU+ solved the issue.

Somebody to update the status for hd51 ?

**Comment by athoik** [comment]
> Somebody to update the status for hd51 ?

**Comment by littlesat** [comment]
Likely the latest drivers did solve this issue... But not comfirmed yet

**Comment by athoik** [comment]
I think problem was on drivers and solved long time ago.
