### ISSUE TITLE
ET10000 misses a few seconds when playing an MP3 (or other audio)

### ISSUE THREAD

**Issue by dAF2000** [OpenPLi/enigma2#429]
If the ET10000 kernel is newer than 3.17.3, I miss a few seconds at the start of each audio file. The sound is just muted (output was SPDIF). Currently, a newer kernel is used which seems to have old bugs again.

See: http://forums.openpli.org/topic/42849-et10000-mogelijkheid-om-een-oude-kernel-te-gebruiken/

**Comment by littlesat** [comment]
This issue should be solved by Xtrend, so I think we cannot solve it.
The only thing we can consider is make changes for boxes suffer from this issue to go for a software codec instead of user the hardware codec.

**Comment by littlesat** [comment]
Driver issue we cannot solve....
