### ISSUE TITLE
Subtitles distorted if centered

### ISSUE THREAD

**Issue by dAF2000** [OpenPLi/enigma2#430]
(DVB) subtitles may become distorted if "Center DVB subtitles" is switched on. See next screenshots. Tested on a ET10000.

![center on](https://cloud.githubusercontent.com/assets/13932898/18449254/c5469038-792e-11e6-9916-356ddc67ffcd.jpg)
![center off](https://cloud.githubusercontent.com/assets/13932898/18449257/ca54af42-792e-11e6-9244-90aaaa62c0e6.jpg)

**Comment by littlesat** [comment]
This does only happen when the broadcaster does not transmit the DVB graphical subtitles correctly in elements and still transmits multiple elements. This simply means these subs cannot be centered. I was thinking about adding a flag per service where you can disable post-processing dvb graphical subtitles and when this flag is set do not post process the subs.

**Comment by littlesat** [comment]
Sorry I did close it by accident...

**Comment by athoik** [comment]
I think we fixed that, can someone confirm it?

**Comment by littlesat** [comment]
Indeed fixed...
