### ISSUE TITLE
Large fonts TuxTxt distorted if PiP active

### ISSUE THREAD

**Issue by dAF2000** [OpenPLi/enigma2#431]
The large fonts in TuxTxt become distorted (wobbly) if PiP is active. See screenshots. Tested on ET10000, Magic SD skin.

![with pip](https://cloud.githubusercontent.com/assets/13932898/18449653/45c5d4ca-7930-11e6-89c2-0a7dd555f4f3.jpg)
![without pip](https://cloud.githubusercontent.com/assets/13932898/18449657/495f15d8-7930-11e6-8f6a-3039e62db528.jpg)

**Comment by ims21** [comment]
It seems, it is for all fonts, if text using "double hight" and is changed y-size.

**Comment by RobvanderDoes** [comment]
Maybe it helps you finding the cause to know that in ViX this issue is not present.

**Comment by ims21** [comment]
under Pli was not problems too ...  may be, some last changes in teletext... 
I do not know - vix have whole system own or is it Pli-derivate or PLi-partially derivate ?

**Comment by RobvanderDoes** [comment]
ViX is a PLi derivate, but diverted a bit (see https://github.com/OpenViX/enigma2 ).

**Comment by ims21** [comment]
I tried put under Pli old fonts (used in vix) and tuttxtlibs and still same. Weird, that could make it python's E2

**Comment by littlesat** [comment]
In python E2's there is nothing rendered... The rendering is completely done in tuxtxt... So it must be something in tuxtxt binary stuff... Can you post a VIX screenshot Ron?

**Comment by ims21** [comment]
It is a question ... same fonts, tried Vix's libs ... same . Enigma's files almost same (nothing about sizes etc).  Installed ViX image - yes, there it is "ok" - there txt seems as it is running in SD (diacritics on chars are not visible well, all is as blurry).

**Comment by ims21** [comment]
init 4
then there in /etc/tuxtxt/tuxtxt2.conf change TTFShiftY **0** to TTFShiftY **2**
init 3

**Comment by athoik** [comment]
Maybe we should change `TTFShiftY 2` to tuxtxt2.conf ?

**Comment by athoik** [comment]
Are we going to fix this one by updating config tuxtxt2.conf?

**Comment by ims21** [comment]
I think, It could be done...

**Comment by littlesat** [comment]
As far I know solved... after a long long time
