### ISSUE TITLE
meta for recordings using service reference and not service name

### ISSUE THREAD

**Issue by ims21** [OpenPLi/enigma2#449]
It is cosmetic only - If provider change transponder, for recorded movie is displayed wrong service name.
There could be name stored into meta (it is on first line): service_ref|service_name (or service_refservice_name)
Reading then ... if exist '|' split first line to service_ref and service_name (or split after last ':'). And if service name is not empty, then use for info about recorded movie this name and not name from lamedb via service_reference. 

Exist easy way (2 lines in .py) - take service name from name of recorded movie (but for user using "short name" will be still wrong)

**Comment by littlesat** [comment]
Service refernce should be kept... But we should consider at least to add a field for the 'current' servicename

**Comment by ims21** [comment]
I think, it it solved long time in meta...
