### ISSUE TITLE
black screen after enabling PiP on encrypted channels

### ISSUE THREAD

**Issue by p1otr** [OpenPLi/enigma2#507]
Every single time I enable PIP on VuSoloSEv2 (or try to record something, same effect), the picture goes to the small window, the fullscreen one turns black. Changing channel in the small window or in the fullscreen results with a black screen as well, no matter which channel I select, including the originally selected one. Bitrate viewer plugin indicates the channel works fine, so is oscam (it decodes the right channel)... the only problem is the video and audio is not there.

I currently use unicable LNB, but I tested different ones as well, with a second cable and with a loop through option (I guess I tested all options related to LNB settings, same effect).

Can I help somehow to debug this problem?

PS enigma2-plugin-extensions-pau plugin is installed

**Comment by RobvanderDoes** [comment]
Did you, while this was happening, try 'blue' --> 'green' --> '0' (miltiple times '0') to change the PiP-mode?

**Comment by p1otr** [comment]
I did, changing PIP mode doesn't help. I have to restart the whole receiver to make it work again

**Comment by p1otr** [comment]
additional info: if I start the PIP option on a FTA channel, it works with other FTA channels. Selecting encrypted one - black screen, selecting FTA one again (even from different transponder, so the LNB/unicable setup is correct) - I see 2 pictures.

Encrypted ones are decoded correctly via my local reader - I can see a message in the bar and in oscam's logs, just no picture/sound.

**Comment by littlesat** [comment]
I could not verify this issue

**Comment by p1otr** [comment]
FTR: the problem was in oscam configuration (changing boxtype to dreambox fixed it)
