### ISSUE TITLE
OpenPli media player support for Chrome temp (.crdownload) and Firefox temp (.part)

### ISSUE THREAD

**Issue by rocco99222** [OpenPLi/enigma2#542]
Even if file downloading.

**Comment by technl** [comment]
Part is not an extension.

**Comment by rocco99222** [comment]
Yes .part is an extension used by FireFox temp downloads. (When downloading file)

**Comment by technl** [comment]
Offcourse but .part could be anything so it is not a mediafile by definition.

**Comment by rocco99222** [comment]
I mean the .part extension from firefox, and you must to know where it comes from is you download the video. (maybe option to hide that extension files if you will)
