### ISSUE TITLE
Web-If can't see box time, OpenPli do not give message if time losed.

### ISSUE THREAD

**Issue by rocco99222** [OpenPLi/enigma2#554]
Time is on 1 Jan 1970, lossing current time but don't see that always.
Conot see box time in Web-If (not directly, ofcourse can see it on make screenshot function)
And Open-Pli do not give message if time losed and set too 1 Jan 1970.
Recordings failed.

**Comment by technl** [comment]
This is not a bug but the start of 'unix time'.
This happens if no time info is available, the receiver will receive the correct time from a transponder (after locking a transponder) or a ntp server.

**Comment by rocco99222** [comment]
Know that, but do not mean that. The reqeust is to add time to web-if and display message.

**Comment by technl** [comment]
This is not a bug but the start of 'unix time'.
This happens if no time info is available, the receiver will receive the correct time from a transponder (after locking a transponder) or a ntp server.

**Comment by technl** [comment]
Why ask overhere?
Ask the openweb makers instead of OpenPLi.

**Comment by rocco99222** [comment]
Don't know where i can found the Openweb makers, only found OpenPli.

**Comment by technl** [comment]
Just try google.
