### ISSUE TITLE
File list sort order indicator

### ISSUE THREAD

**Issue by WanWizard** [OpenPLi/enigma2#557]
is not very clear, and most people don't understand the symbols.

See https://forums.openpli.org/topic/46126-opnames-wat-betekent-dit (in Dutch).

It would be better to use "standard" png images for it (https://thenounproject.com/term/sorting/, https://icons8.com/web-app/19163/sort, http://www.flaticon.com/search?word=sort, etc) or icons from the fontawesome collection if we want to have a font-based solution (like http://fontawesome.io/icon/sort-alpha-desc/).

**Comment by ims21** [comment]
Added small help for it into PLi skins for it ...  
- about Sort: press Menu on selected movie and select item "Sort by ..."
- about 2nd serie of pictures ("End of movie") ... define "End of movie (as menu)" - in Movieplayer main setting - for some key and then you will see help (if you press this button on movie) too...

**Comment by RobvanderDoes** [comment]
Or even better: use a 'pull-down list'.

![ml-pl](https://user-images.githubusercontent.com/1040294/28249482-f343a920-6a56-11e7-86dd-b217efbf11d9.jpg)

**Comment by ims21** [comment]
no, you did not understand me
![sort](https://user-images.githubusercontent.com/1208763/28249912-f5f3dd04-6a5e-11e7-97d2-7437b3f7cbbb.jpg)
![end](https://user-images.githubusercontent.com/1208763/28249915-fdaff8fc-6a5e-11e7-96d4-67926367f4d9.jpg)

**Comment by athoik** [comment]
Are we done here? Or issue still stands?

**Comment by ims21** [comment]
Done looong time in PLi skins for this menus... can be closed, imho

**Comment by AbuBaniaz** [comment]
As this is done, who is going to close the issue?

**Comment by AbuBaniaz** [comment]
@wanwizard
Can you close this please

**Comment by WanWizard** [comment]
Yes sir. :smiley:
