### ISSUE TITLE
Adding option to Settings>System>Recordings locations

### ISSUE THREAD

**Issue by rocco99222** [OpenPLi/enigma2#562]
Missing option at:
Standard recordingslocation: last used recording location
(with that recording location behind brackets)

Thank You!

**Comment by technl** [comment]
Don't know what you mean, but nothing is worng with the records location settings.

**Comment by rocco99222** [comment]
Oh... see now at record location timer recordings this option is available.
Don't know why not available at manual recordings, but happy to see it is availble at timer recordings.
