### ISSUE TITLE
Option to mute the screen.

### ISSUE THREAD

**Issue by rocco99222** [OpenPLi/enigma2#565]
In a situation i want to use NPOs HBB TV but i do not want to see the pinkpop or lowlands crap on NPO  #3, and NPO 1 is broadcasting the Top 2000 cafe crap, what i also do not want to see. On NPO 2 there is broadcast a  popquiz or another (pop)music crap.

Want to mute the screen without the sound. Please not advice to use (AV)receiver or other external sound system. Sound can been mute with mute button, or on external receiver or barebone.

I request the feature to mute the video of the TV channel without the sound. When mute screen, want to display black screen, OpenPli bootscreen, own choosing image or the radio background. (preffer OpenPli bootscreen or own image)

Mute video picture can also been usefull on a TV channel where you only will listen to the nature surroundings as MyZen.TV, Mute TV or Stingray Ambiance.
Or a pop crap channel as Xite.

Thanks

**Comment by technl** [comment]
Stop bugging us.
