### ISSUE TITLE
Block EIT EPG per channels

### ISSUE THREAD

**Issue by pr2git** [OpenPLi/enigma2#568]
Hi,

I'd like to keep EIT EPG current/next enable and use EPG Import (Rytec) at the same time. This is useful when there are last minutes changes in EPG.
For some channels, Rytec provides a proper full EPG while EIT current/next always send: "Detailled program not available". So the Rytec EPG provides informations but it is overwritten by the EIT current/next informations in the 1st infobar.

Would be nice to have in the contextual menu an option to disable EIT EPG per channels. (Like we have for Parental protection) so I can keep EIT current/next enable and select on which channels I don't want this feature enabled.

Pr2

**Comment by RobvanderDoes** [comment]
I would like to extend this proposal to ALL EIT EPG data, not just Now/Next.

**Explanation:** 
Rytec (logically) doesn't provide EPG for all services that are available on satellites. So to obtain EPG-data for those services, the use of EIT is required (provided they send any readable EPG at all). Not being able to suppress EIT for services that are covered by Rytec means double, and often not identical, data for those services, which is very inconvenient.

**Comment by RobvanderDoes** [comment]
'Closed' as in 'fixed'?

**Comment by pr2git** [comment]
Yes when a channel get its EPG from Rytec/EPGImport it is flagged so it doesn't get the EIT EPG.

**Comment by RobvanderDoes** [comment]
Ah, good, I missed that one.
Would be nice if the plugin would have some hint-text; a.o. stating this important information.

**Comment by pr2git** [comment]
No I can't because this is done at Enigma2 level not at the importer level, I wrote EPGImport in my previous message but this is true for any external EPG loader application.

Here is the change:
https://github.com/OpenPLi/enigma2/commit/81cf60d2d72b73c52f577bcaec829821dd31a678

**Comment by RobvanderDoes** [comment]
Ah, that sounds good!
Just to be sure: this applies also when using Cross-EPG? So one can use both Rytec (and/or Cross) & EIT/Freesat/etc without them interfering?

**Comment by pr2git** [comment]
AFAIK yes.
