### ISSUE TITLE
Hotkey: Key discovery mode

### ISSUE THREAD

**Issue by pr2git** [OpenPLi/enigma2#572]
Can we imagine to have in the bottom a new option (color button blue for exemple assigned), that will switch into a "key discovery mode".
 
In this mode by pressing the keys on the RCU it will show up which "name" and "internal value" this key has in Hotkey.
 
So people searching which name is associated with a key can saw it in Hotkey. 
 
We can start by just displaying the name and later on we can also imagine to reuse the Wizard remote control (or the OpenWebif One) on this screen and show which key is pressed with its associated name to make it user friendly.
 
This will also allows help end-users and developpers to report RCU "wrong" key assignment (or missing one), like in the exemple where we don't know to what is assigned the miraclebox "blue box" key and that should normally open the mediaplayer, or the FAV button.
 
Today there is no tools to press a RCU key and know what which name it refers too.
 
Exit key will leave this mode, I think that this key exist on every RCU and is always properly assigned (like the color buttons too I guess).

**Comment by persianpros** [comment]
I think this would help you: https://github.com/OpenPLi/enigma2/pull/998
But only when you debug enigma2 not in GUI.
