### ISSUE TITLE
Recording: stored the original channel name and not the service reference

### ISSUE THREAD

**Issue by pr2git** [OpenPLi/enigma2#573]
Hi,

When recording the metadata are stored too (which is nice for the full program description), but not the "real service name" on the time of recording, only the service reference is stored.

Problem is that I have records done since many years on my HDD and the service reference of the channel changed since it was recorded. But the channel name displayed is always based on the current lamedb informations, so the channel name I record from is no longer the "real service name" but the today "service name". Or channel that simply no longer exist at all, so we lose some useful information with the current way of storing the record informations.

Sometimes some service references turn into adult channels and vice-versa so blocking based on blacklist/whitelist is no more relevant for recording. Would be better to store if the recording was blacklisted at the time of recording than reusing the today situation. So with satellite channel changes some "sensitive" content can be unlocked and some no-sensitive can became "sensitive".

French CanalSat is specialized in changing there whole channels service reference every 3 months.

Pr2

**Comment by ims21** [comment]
But it was solved long time ago [here](https://github.com/OpenPLi/enigma2/commit/e38e02a784f3afca39508486e26fe6d6c58b1c24)

From this date are service name for recording displayed well

**Comment by athoik** [comment]
Is this issue valid or we can close it?

**Comment by ims21** [comment]
solved ...
