### ISSUE TITLE
Display icon when is multiple audio channel and when are in differend languages.

### ISSUE THREAD

**Issue by rocco99222** [OpenPLi/enigma2#576]
Maybe SL (single language) or ML (mutiple language)?

**Comment by technl** [comment]
On most of the channels multiple audio is available so a new annoying icon will be coninue visible.
Bad idea and again, it is not an issue but a request ....

**Comment by technl** [comment]
On most of the channels multiple audio is available so a new annoying icon will be coninue visible.
Bad idea and again, it is not an issue but a request ....

**Comment by technl** [comment]
Stop annoying us.

**Comment by rocco99222** [comment]
Most of channels? Maybe you mean Dolby 5.1 surround. But multiple audio only availe at a channel of 10?

At Digitenne only featured a second audio channel on NPO 1/2/3 that featuring the GOS channel.

**Comment by technl** [comment]
Just push the yellow button and you'll get an overview of available channels.

**Comment by technl** [comment]
Please swith over to vti and stop bugging us.
