### ISSUE TITLE
When play video in folder that have mutiple video's there is no counting number in the video screen.

### ISSUE THREAD

**Issue by rocco99222** [OpenPLi/enigma2#577]
Exsample:

20:50

movie.ts

0:00:04   - 2:00:45

II            720x576i25                               16:9

Missing: 3/7 in interface.

I can not see how much video's to go in the play screen.

I do not have the need to have it in the files list but at the video themselves i missing it. Because i canot see the other video files in the list.

**Comment by technl** [comment]
Then try to find out how your device is working.
You're really the first, and only person in the world who complains.
