### ISSUE TITLE
HDMI-Cec some keys are not working

### ISSUE THREAD

**Issue by kami83** [OpenPLi/enigma2#628]
Since i Upgraded to VTi 11.0 some of my remote keys from my Philips TV are not working over HDMI CEC. Timeshift, Rec,.. are not reacting. But if i look at the log they are listed:

[VTI HDMI-CEC] received cec message 44 from 0
[VTI HDMI-CEC] received cec message part two 45 from 0
[VTI HDMI-CEC] received cec message 45 from 0
[VTI HDMI-CEC] received cec message 44 from 0
[VTI HDMI-CEC] received cec message part two d from 0
[VTI HDMI-CEC] received cec message 45 from 0
[VTI HDMI-CEC] received cec message 44 from 0
[VTI HDMI-CEC] received cec message part two 47 from 0
[VTI HDMI-CEC] received cec message 45 from 0
[VTI HDMI-CEC] received cec message 44 from 0
[VTI HDMI-CEC] received cec message part two 47 from 0
[VTI HDMI-CEC] received cec message 45 from 0
[VTI HDMI-CEC] received cec message 44 from 0
[VTI HDMI-CEC] received cec message part two 45 from 0
[VTI HDMI-CEC] received cec message 45 from 0
[VTI HDMI-CEC] received cec message 44 from 0
[VTI HDMI-CEC] received cec message part two 44 from 0
[VTI HDMI-CEC] received cec message 45 from 0

Can someone help me with this? In 9.5 everything was working fine.

Thanks a lot.
Cu kami83

**Comment by betacentauri** [comment]
This is OpenPLi git! Ask VTi to fix it.

**Comment by kami83** [comment]
Ohh i am sorry. I thought you support this plugin. Can you tell me where i can find the HDMI-CEC support?

**Comment by betacentauri** [comment]
HDMI CEC plugin is part of E2. VTi uses own E2 with closed source. We cannot fix it. Please ask VTi. Maybe here https://www.vuplus-support.org

**Comment by littlesat** [comment]
Vti issue not openpli
