### ISSUE TITLE
Web-if remote, missing button to turn of TV (not the STB)

### ISSUE THREAD

**Issue by rocco99222** [OpenPLi/enigma2#629]
Missing the left button to turn off TV. In the web-if remote.

**Comment by technl** [comment]
What do we have to do with openwebif in enigma2 branch???
Stop with your annoying wishes. Tomorrow you'll ask for a special button in the openwebif to lower or raise your bed.

**Comment by technl** [comment]
What do we have to do with openwebif in enigma2 branch???
Stop with your annoying wishes. Tomorrow you'll ask for a special button in the openwebif to lower or raise your bed.
