### ISSUE TITLE
Possibility to select saving location of epg.dat in EPG settings

### ISSUE THREAD

**Issue by Dream1975** [OpenPLi/enigma2#829]
Made ticket in request of Wanwizard:

Select the location of epg.dat in menu-settings-system-EPG settings (so you can choose to store the file on HDD/USB/share etc)
 
The location can be stored in /etc/enigma/settings using config.misc.epgcache_filename=/media/usb/epg.dat

See https://forums.openpli.org/topic/48606-rrytec-xmltv-sources-saved-epgdat-on-hhd-or-usb/#entry680144

**Comment by ims21** [comment]
You can use EPGRefresh plugin or HDD Sleep plugin where is this option...

**Comment by Dream1975** [comment]
That is true. But in my opinion, as this is a setting for enigma2 it would seem right to also be able to set it in enigma2 instead of through an external plugin

**Comment by AbuBaniaz** [comment]
OE-A images have this. Perhaps someone can pick it in?

**Comment by RobvanderDoes** [comment]
There is no such thing as 'OE-A images'; all are different. The only common factor is the use of a common OE-environment. So it would be better to point to the specific code in a specific image.

But besides: PLi has expressed several times they will not embed such a functionality.

**Comment by persianpros** [comment]
You can find which files you need to change after reading these commits:
https://github.com/openatv/enigma2/commit/c48a379fe7e351f18250c3ce3230a888bb0574a9
https://github.com/openatv/enigma2/commit/0b09abc3b50a411ff65b91de1a331c9a638f1cc0
https://github.com/openatv/enigma2/commit/a6dff332c368d43c43d64b007fd4f4349c4539f0

**Comment by littlesat** [comment]
UThe way how they get a list of media don’t work. When you jnstantly insert an usb stick it Will not be added without an e2 restart. In addition you can only move it to a root of a media. With what I made you can put it on any location you want. I agree less user frendly... when doing it right we also need a good path selection within a config first... we better can move it to expert level. Usually actually you don’t need this config at all. I just add it for testing... So I prefer even to revert it as a plugin can do it ;)

**Comment by littlesat** [comment]
Done
