### ISSUE TITLE
Add standby when not watched to HDMI-CEC

### ISSUE THREAD

**Issue by 3djc** [OpenPLi/enigma2#883]
I have a setup with an HD2400, Denon AVR Amp, LG Oled, all working great with hdmi-cec

However, when starting another device, like nVidia shield for example, the new device request been displayed, which works fine, the AVR switches input, but since HD2400 is not watched anymore, it should go to standby until been displayed again (if I manually put it into standby using hd2400 remote, it turn off the tv and amp too),

**Comment by ims21** [comment]
enable in setting "Detect next boxes before standby" and you can put box to standby (if your nVidia follows rules of CE protocol and can report power status...) without turn of AVR and TV.

Automatic go to standby, if is active diferent input on TV is not standard... , imho
