### ISSUE TITLE
Why PLi is still releasing images for old Dreamboxes ?

### ISSUE THREAD

**Issue by persianpros** [OpenPLi/enigma2#920]
I'm not sure this the right place to talk about this matter or not but why do you still keep dreambox stuff in enigma2 itself and some old bsp files for discontinued products ?
Dreambox abandoned open source scene and it seems they're happy with what they have (Just like apple and its customers) so why bother keep some dream related things ?
It's like PLi stuck in the middle of something, Not 100% support and not 0% for good, really what's the point of this ?
We can clean enigma2 and the OE for Open PLi 5 release and let go of dreambox once for all as there are plenty of new STBs.
It's not your duty to support a brand that does not want your help and with some websites like http://www.pli-images.net you can ignore this brand.

**Comment by ims21** [comment]
because many of members using still dmm boxes ? :-)

**Comment by persianpros** [comment]
They can use Open PLi 4 for sure, Isn't it better for Open PLi 5 to be a fresh and new start ?

**Comment by WanWizard** [comment]
Support for all DMM hardware, except the DM8000, will be dropped with the next release.
