### ISSUE TITLE
adenin's debug

### ISSUE THREAD

**Issue by persianpros** [OpenPLi/enigma2#932]
Hi PLi team,
Do you think we need this https://github.com/openatv/enigma2/commit/b2a4c50206973ed65134434ee50ef61d09232166 ?
I can adapt it for PLi but it requires time so if you think it's a good thing to have let me know :)

**Comment by WanWizard** [comment]
Personally I don't really see the benefit.

**Comment by persianpros** [comment]
And one more question: When I sign some commits they get verified status but after littlesat merges them they will loose the verified status, Is this the way it should be ?

**Comment by WanWizard** [comment]
I assume he's using github's standard PR merge feature, so maybe it's a display thing?
